openapi: 3.0.1
info:
  title: Url Shortener API definitions
  description: 'This is a sample interface description for my demo project Url Shortener.
  In this project you can add urls and define a shorter url for it, let the system choose some name for it. UwU'
  contact:
    email: hakuhun@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://localhost:8010
tags:
  - name: Url Shortener
    description: Describe elements required to an url shortener
paths:
  /url/shorten:
    post:
      tags:
        - Alias creation
      summary: Add a new url to redirect to a page with a shorter alias
      operationId: addShortenedUrl
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
      requestBody:
        description: An object what represents a shortened alias.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlAlias'
        required: true
      responses:
        201:
          description: CREATED - A new alias has been created
        401:
          description: UNAUTHORIZED - No acces right for the requested operation
        403:
          description: ALREADY_USED - This happens when the provided alias has been used for anouther shortening.
        405:
          description: Invalid input
          content: {}
      security:
        - ApiKeyAuth: []
  /url/report/{requestedAlias}:
    patch:
      tags:
        - File a report to an alias
      summary: A way to report unwanted and inappropriate aliases.
      operationId: reportAlias
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
        - name: requestedAlias
          in: path
          description: the alias of a shortened url
          required: true
          schema:
            type: string
      requestBody:
        description: An object what represents a shortened alias.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlAlias'
      responses:
        200:
          description: OK - a user report has been added to the alias as a flag
        401:
          description: UNAUTHORIZED - No acces right for the requested operation
        404:
          description: NOT_FOUND - the reported alias does not exists
      security:
        - ApiKeyAuth: [ ]
  /redirect/{requestedAlias}:
    get:
      tags:
        - Redirecting
      summary: Redirecting a user with an alias to the original link
      operationId: redirectingToOriginal
      parameters:
        - name: requestedAlias
          in: path
          description: the alias of a shortened url
          required: true
          schema:
            type: string
      responses:
        301:
          description: A redirect to another page
          content: {}
        404:
          description: NOT_FOUND - the alias does not exists
components:
  schemas:
    UrlAlias:
      type: object
      required: [originalUrl]
      properties:
        id:
          type: string
        originalUrl:
          type: string
        requestedAlias:
          type: string
        report:
          $ref: '#/components/schemas/Report'
        requester:
          $ref: '#/components/schemas/Requester'
        status:
          type: string
          enum: [ READY, COMPROMISED, DELETED ]
        creationDate:
          type: string
          format: date
    Requester:
      type: object
      properties:
        email:
          type: string
    Report:
      properties:
        email:
          type: string
        reason:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
