spring:
  application:
    name: url-shortener
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://urlAliases:urlAliases@localhost:27017/urlAliases
      auto-index-creation: true

management:
  server:
    port: 9015
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8010
  tomcat:
    max-threads: 400
    max-connections: 400
    accept-count: 40

api:
  keys:
    publicApiKey:
      accessTo: create, report
    internalTesting:
      accessTo: "*"
    backOffice:
      accessTo: create, report, listReport