spring:
  application:
    name: url-shortener
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://sern_admin:sern_admin_password@localhost:27017/urlShorts
      auto-index-creation: true

management:
  server:
    port: 9015
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8010
  tomcat:
    max-threads: 400
    max-connections: 400
    accept-count: 40